import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import { AnalysisProvider } from './contexts/Analysiscontext';

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import { NavbarMinimal } from "./components/navbar/navbarminimal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Adjust the width as needed for your navbar
  const navbarWidth = "220px";

  return (
   
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
      <AnalysisProvider>
        <MantineProvider>
         
          <NavbarMinimal />
          <main style={{marginLeft :"220px"}}>
         
            {children}
          </main>
         
        </MantineProvider>
        </AnalysisProvider>
      </body>
    </html>
   
  );
}
