import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import { AnalysisProvider } from './contexts/Analysiscontext';

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import { NavbarMinimal } from "./components/navbar/navbarminimal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Adjust the width as needed for your navbar
  const navbarWidth = "220px";

  return (
   
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
      <AnalysisProvider>
        <MantineProvider>
         
          <NavbarMinimal 
            sx={(theme) => ({
              backgroundColor: theme.colors.indigo[6],
              padding: theme.spacing.md,
              borderRadius: theme.radius.md,
            })}
          >
            <Navbar.Section component={Link} href="#" variant="subtle">
              <Navbar.Divider />
              <Group position="apart">
                <Text weight={500} size="lg">
                  Create Next App
                </Text>
                <ActionIcon>
                  <IconSettings size={18} />
                </ActionIcon>
              </Group>
            </Navbar.Section>
          </NavbarMinimal>
          <main style={{marginLeft :"220px"}}>
         
            {children}
          </main>
         
        </MantineProvider>
        </AnalysisProvider>
      </body>
    </html>
   
  );
}
